environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_REFERENCE: "npcap-wpcap/0.93"
    CONAN_USERNAME: "bincrafters"
    CONAN_LOGIN_USERNAME: %BT_USER%
    CONAN_LOGIN_PASSWORD: %BT_KEY%
    CONAN_CHANNEL: "stable"
    VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"
    CONAN_UPLOAD: "https://bintray.com/%CONAN_USERNAME%/public-conan"
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

platform:
  - x86
  - x64
  
configuration:
  - Release
  - Debug 
  
install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
